provider "aws" {
    region = "eu-west-2"
    access_key = "********************"
    secret_key = "********************"
}

resource "aws_iam_user" "myuser" {
    name = "user1"
}

resource "aws_iam_policy" "customPolicy" {
    name = "GlacierEC2123"

    policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "ec2:DeleteManagedPrefixList",
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:ReplaceRouteTableAssociation",
                "ec2:ModifyManagedPrefixList",
                "elasticfilesystem:PutAccountPreferences",
                "ec2:DeleteVpcEndpoints",
                "ec2:ResetInstanceAttribute",
                "ec2:RejectTransitGatewayMulticastDomainAssociations",
                "ec2:ResetEbsDefaultKmsKeyId",
                "ec2:AttachInternetGateway",
                "ec2:ReportInstanceStatus",
                "ec2:ModifyVpnConnectionOptions",
                "ec2:DeleteVpnGateway",
                "ec2:CreateRoute",
                "elasticfilesystem:ClientMount",
                "ec2:GetEbsDefaultKmsKeyId",
                "ec2:DeleteNetworkInsightsAnalysis",
                "ec2:UnassignPrivateIpAddresses",
                "ec2:DisableImageDeprecation",
                "ec2:CancelExportTask",
                "ec2:DeleteTransitGatewayPeeringAttachment",
                "ec2:ImportKeyPair",
                "ec2:AssociateClientVpnTargetNetwork",
                "ec2:StopInstances",
                "ec2:CreateVolume",
                "ec2:ReplaceNetworkAclAssociation",
                "ec2:CreateVpcEndpointServiceConfiguration",
                "ec2:CreateNetworkInterface",
                "ec2:CancelSpotInstanceRequests",
                "ec2:CreateTransitGatewayRoute",
                "ec2:CreateTransitGatewayVpcAttachment",
                "ec2:EnableImageDeprecation",
                "ec2:DeleteDhcpOptions",
                "ec2:DeleteNatGateway",
                "ec2:CancelCapacityReservation",
                "elasticfilesystem:ClientRootAccess",
                "ec2:EnableTransitGatewayRouteTablePropagation",
                "ec2:ModifyVpcEndpoint",
                "ec2:DeleteQueuedReservedInstances",
                "ec2:ModifyInstanceCapacityReservationAttributes",
                "ec2:CreateVpnConnection",
                "ec2:DeleteSpotDatafeedSubscription",
                "ec2:ImportVolume",
                "ec2:DeleteTransitGatewayPrefixListReference",
                "ec2:MoveAddressToVpc",
                "elasticfilesystem:CreateFileSystem",
                "ec2:ModifyFleet",
                "ec2:RunScheduledInstances",
                "ec2:ModifyIdentityIdFormat",
                "ec2:CreateVpc",
                "ec2:RequestSpotFleet",
                "ec2:WithdrawByoipCidr",
                "ec2:CreateSubnetCidrReservation",
                "ec2:ReleaseHosts",
                "ec2:DeleteTransitGatewayMulticastDomain",
                "ec2:ModifySubnetAttribute",
                "ec2:DeleteNetworkInsightsPath",
                "ec2:CreateSnapshot",
                "elasticfilesystem:PutLifecycleConfiguration",
                "ec2:DeleteLaunchTemplateVersions",
                "elasticfilesystem:CreateAccessPoint",
                "ec2:DeleteNetworkAcl",
                "ec2:ModifyReservedInstances",
                "ec2:ReleaseAddress",
                "ec2:ModifyInstanceMetadataOptions",
                "ec2:AssociateDhcpOptions",
                "ec2:ModifyInstancePlacement",
                "ec2:CreateTrafficMirrorTarget",
                "ec2:ModifyTrafficMirrorFilterRule",
                "ec2:CreateClientVpnRoute",
                "ec2:AttachVpnGateway",
                "ec2:CreateLocalGatewayRoute",
                "ec2:ProvisionByoipCidr",
                "ec2:AssociateTransitGatewayMulticastDomain",
                "ec2:CreateVpnConnectionRoute",
                "ec2:DisableSerialConsoleAccess",
                "ec2:ModifyVpnTunnelOptions",
                "ec2:DeleteVpcEndpointConnectionNotifications",
                "ec2:RestoreAddressToClassic",
                "ec2:DeleteCustomerGateway",
                "ec2:DeleteClientVpnRoute",
                "ec2:EnableVgwRoutePropagation",
                "elasticfilesystem:Backup",
                "ec2:ModifyVpcTenancy",
                "ec2:ApplySecurityGroupsToClientVpnTargetNetwork",
                "ec2:ConfirmProductInstance",
                "elasticfilesystem:DescribeMountTargetSecurityGroups",
                "elasticfilesystem:DescribeBackupPolicy",
                "ec2:GetPasswordData",
                "ec2:CreateDefaultVpc",
                "ec2:DescribeScheduledInstances",
                "ec2:GetAssociatedIpv6PoolCidrs",
                "ec2:DisassociateIamInstanceProfile",
                "ec2:CreateSnapshots",
                "ec2:CreateSubnet",
                "elasticfilesystem:DeleteFileSystem",
                "ec2:DeleteNetworkAclEntry",
                "ec2:AttachVolume",
                "ec2:ExportImage",
                "ec2:DisassociateAddress",
                "ec2:ExportTransitGatewayRoutes",
                "ec2:AssociateInstanceEventWindow",
                "ec2:CreateNatGateway",
                "ec2:AcceptTransitGatewayPeeringAttachment",
                "ec2:ModifyTrafficMirrorFilterNetworkServices",
                "ec2:ModifyVpnConnection",
                "ec2:StartNetworkInsightsAnalysis",
                "elasticfilesystem:ClientWrite",
                "ec2:ModifyImageAttribute",
                "ec2:ExportClientVpnClientCertificateRevocationList",
                "ec2:EnableFastSnapshotRestores",
                "ec2:RejectTransitGatewayPeeringAttachment",
                "ec2:CreateDefaultSubnet",
                "ec2:CreateCapacityReservation",
                "ec2:CreateSpotDatafeedSubscription",
                "ec2:ModifyVpnTunnelCertificate",
                "elasticfilesystem:DeleteMountTarget",
                "ec2:ModifyInstanceEventWindow",
                "ec2:RebootInstances",
                "ec2:CreateInstanceExportTask",
                "ec2:DeleteTrafficMirrorFilter",
                "ec2:DeleteLaunchTemplate",
                "ec2:CreateRestoreImageTask",
                "ec2:AssignIpv6Addresses",
                "ec2:ImportInstance",
                "ec2:AssociateEnclaveCertificateIamRole",
                "ec2:AcceptVpcEndpointConnections",
                "ec2:ModifyFpgaImageAttribute",
                "ec2:CancelConversionTask",
                "ec2:ImportSnapshot",
                "ec2:RevokeClientVpnIngress",
                "ec2:DeleteTrafficMirrorSession",
                "ec2:DisassociateSubnetCidrBlock",
                "ec2:RegisterTransitGatewayMulticastGroupMembers",
                "ec2:AuthorizeClientVpnIngress",
                "ec2:CreateLaunchTemplate",
                "ec2:ImportClientVpnClientCertificateRevocationList",
                "ec2:DisableVpcClassicLink",
                "ec2:DisableVpcClassicLinkDnsSupport",
                "ec2:GetManagedPrefixListAssociations",
                "ec2:AllocateHosts",
                "elasticfilesystem:PutBackupPolicy",
                "ec2:CancelImportTask",
                "ec2:DeleteInstanceEventWindow",
                "ec2:ModifyIdFormat",
                "elasticfilesystem:UpdateFileSystem",
                "ec2:DeleteFlowLogs",
                "ec2:CopySnapshot",
                "ec2:ModifyVpcEndpointServiceConfiguration",
                "ec2:UnmonitorInstances",
                "ec2:RegisterInstanceEventNotificationAttributes",
                "ec2:DetachClassicLinkVpc",
                "ec2:MonitorInstances",
                "ec2:DeleteVpcPeeringConnection",
                "ec2:CreateTransitGatewayRouteTable",
                "ec2:AcceptVpcPeeringConnection",
                "ec2:ModifyTransitGateway",
                "ec2:DescribeVolumesModifications",
                "ec2:DeregisterInstanceEventNotificationAttributes",
                "ec2:DisableVgwRoutePropagation",
                "ec2:CreateTransitGatewayConnectPeer",
                "ec2:CreateTransitGateway",
          
                "ec2:ResetFpgaImageAttribute"
            ],
            "Resource": "*"
        }
    ]
}
EOF
}

resource "aws_iam_policy_attachment" "policyBind" {
    name = "attachment"
    users = [aws_iam_user.myuser.name]
    policy_arn = aws_iam_policy.customPolicy.arn
}


